# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.29
_src_path: git+https://github.com/OCA/oca-addons-repo-template
ci: GitHub
convert_readme_fragments_to_markdown: false
enable_checklog_odoo: false
generate_requirements_txt: true
github_check_license: true
github_ci_extra_env: {}
github_enable_codecov: true
github_enable_makepot: true
github_enable_stale_action: true
github_enforce_dev_status_compatibility: true
include_wkhtmltopdf: false
odoo_test_flavor: OCB
odoo_version: 12.0
org_name: Odoo Community Association (OCA)
org_slug: OCA
rebel_module_groups: []
repo_description: 'This project aims to deal with modules related to the webclient
    of Odoo. You''ll find modules that:


    - Add facilities to the UI

    - Add widgets

    - Ease the import/export features

    - Generally add clientside functionality'
repo_name: Web addons for Odoo
repo_slug: web
repo_website: https://github.com/OCA/web

